Repository MeryHarikaG/slash-phase5, pull requests merged in 2023-11, with the labels that each got.

#1 New Feature: Sorting based on price
  src/pages/search.py
Labels: enhancement

#2 New Feature: Sorting based on price
  src/pages/search.py
Labels: enhancement

#4 Bug Fix: Cheapest product link
  src/pages/search.py
Labels: bug

#5 UI Designing: Search results heading
  assets/style.css
  src/pages/search.py
Labels: enhancement

#6 UI Designing: Search results heading
  assets/style.css
  src/pages/search.py
Labels: enhancement

#7 UI Designing: Slash - Product Search
  assets/style.css
  slash_user_interface.py
  src/pages/search.py
Labels: enhancement

#8 UI Designing: Slash - Product Search
  assets/style.css
  slash_user_interface.py
  src/pages/search.py
Labels: enhancement

#9 UI: Highlight cheapest product & heading
  assets/style.css
  src/pages/search.py
Labels: enhancement

#10 UI: Highlight cheapest product & heading
  assets/style.css
  src/pages/search.py
Labels: enhancement

#11 Data formatting: 'Price' field from API
  src/pages/search.py
Labels: bug

#12 Data formatting: 'Price' field from API
  src/pages/search.py
Labels: bug

#13 Bug Fixes: Web scraping
  src/configs.py
  src/configs_mt.py
  src/main_streamlit.py
  src/pages/search.py
  src/scraper.py
  src/scraper_mt.py
Labels: bug

#14 Bug Fixes: Web scraping
  src/configs.py
  src/configs_mt.py
  src/main_streamlit.py
  src/pages/search.py
  src/scraper.py
  src/scraper_mt.py
Labels: bug

#15 Data formatting: 'Price' from all the websites
  src/pages/search.py
Labels: bug

#16 Data formatting: 'Price' from all the websites
  src/pages/search.py
Labels: bug

#17 New features: Min-Price, Max-Price & success msg
  src/pages/search.py
Labels: enhancement

#18 New features: Min-Price, Max-Price & success msg
  src/pages/search.py
Labels: enhancement

#25 UI Enhancement: Created a 2-column layout
  src/pages/search.py
Labels: enhancement

#26 UI Enhancement: Created a 2-column layout
  src/pages/search.py
Labels: enhancement

#27 Display proper msg if no results returned from API
  src/pages/search.py
Labels: bug

#28 Multiple commits from tbattul & MeryHarikaG
  Code_Of_Conduct.md
  LICENSE
  src/pages/search.py
Labels: bug

#32 Update README.md
  README.md
Labels: documentation

#35 Added conditions for saving WishList
  src/pages/search.py
Labels: enhancement

#36 Added conditions for saving WishList
  CONTRIBUTING.md
  README.md
  src/pages/search.py
Labels: enhancement

#38 Update search.py
  src/pages/search.py
Labels: bug

#40 Update wishlist.py
  src/pages/wishlist.py
Labels: bug

#41 Update login.py
  src/pages/login.py
Labels: enhancement

#39 Tbattul dev2
  src/pages/search.py
Labels: duplicate

#43 Merge Main to Project3
  README.md
  src/pages/login.py
  src/pages/search.py
  src/pages/wishlist.py
Labels: enhancement

#52 Update README.md with badges
  README.md
Labels: documentation

#51 Update README.md with Phase 5 Enhancements
  README.md
Labels: documentation

#53 Update README.md with badges
  README.md
Labels: documentation

#55 Updated CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#62 Update README.md
  README.md
Labels: documentation

#65 Add Code Description for Phase 5
  docs/Code Description_Phase-5.pdf
Labels: documentation

#81 Update SoftwareDocumentation- Phase5.md
  docs/SoftwareDocumentation- Phase4.md
Labels: documentation

#86 Update README.md
  README.md
Labels: documentation

#90 Update README.md
  README.md
Labels: documentation

#82 Rename SoftwareDocumentation- Phase4.md to SoftwareDocumentation- Pha…
  docs/SoftwareDocumentation- Phase5.md
Labels: documentation

#93 Update SoftwareDocumentation-Phase 5.md
  docs/SoftwareDocumentation-Phase 5.md
Labels: documentation

#95 Adding evidence for video in rubric
  Project 3/Project 3rubric.md
Labels: documentation

#96 Update Improvements-phase5.md
  docs/Improvements-phase5.md
Labels: documentation

#97 Create README.md in proj3 branch
  Project 3/README.md
Labels: documentation
